### ISSUE TITLE
trouble with requirements.txt

### ISSUE THREAD

**Issue by vjcitn** [YosefLab/totalVI_reproducibility#14]
Should it be possible to recreate the stack underlying the analyses using `pip install -r requirements.txt`?  I am no python expert and am trying this and hitting
```
Collecting Cython==0.29.14
  Using cached Cython-0.29.14.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Unable to find pgen, not compiling formal grammar.
      running egg_info
      creating /tmp/pip-pip-egg-info-c_lhjhdp/Cython.egg-info
      writing /tmp/pip-pip-egg-info-c_lhjhdp/Cython.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-c_lhjhdp/Cython.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-pip-egg-info-c_lhjhdp/Cython.egg-info/entry_points.txt
      writing top-level names to /tmp/pip-pip-egg-info-c_lhjhdp/Cython.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-c_lhjhdp/Cython.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-72hyy90q/cython_d172ea3a44ce4c76b283a0eacc9bff80/setup.py", line 228, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
...
```
Any advice appreciated; if there is a container around that can be used that would be great.  (N.B., Cython is not the only package spec in requirements.txt that can't be satisfied.  There seem to be many.)

**Comment by adamgayoso** [comment]
Which analysis are you trying to reproduce? totalVI can be used through the [scvi-tools](https://scvi-tools.org) package with tutorial [here](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/totalVI.html)

**Comment by vjcitn** [comment]
Thanks, I was trying to run Background_111day1.ipynb.

**Comment by vjcitn** [comment]
The tutorial notebook crashed in colab at "Now we can compute clusters and visualize the latent space."  For lack of RAM.  I thought I saw a recommendation upon starting that a higher-RAM instance would be needed but I can't find it.

**Comment by vjcitn** [comment]
We can close this.  More recently the colab notebook succeeded.  Also https://vjcitn.github.io/scviR/ may be of interest - conveys some intermediate objects along the analysis pathway to help R users explore the framework.
